### PR TITLE
Change minimal Go version to 1.21 and removed unnecessary test

### PR DESCRIPTION
**Pull request by edmocosta**
- Changed minimal go version to 1.21 (stable version), so other libraries does not need to bump their Go versions to use it. 
- Considering this library is not using (and probably won't use in the future) Goroutines, we can safety remove the `package_test` Goroutines leakage checks and avoid adding unneeded external decencies to the library.

### CODE REVIEW

**Review by jsvd — COMMENTED** [review]
There is no reason given in the PR or the commit for the go version downgrade and removal of the test, can we add that to the commit message?

**Comment by edmocosta** [comment]
> There is no reason given in the PR or the commit for the go version downgrade and removal of the test, can we add that to the commit message?

Hey @jsvd, I've added it on the PR description! thanks for reviewing :)

**Review by jsvd — APPROVED** [review]
Overall LGTM, I noticed you bumped .go-version again, maybe we could also bump versions in .golangci.yml so the library is tested with the most recent golang, even if it supports an older one.

**Comment by edmocosta** [comment]
> Overall LGTM, I noticed you bumped .go-version again, maybe we could also bump versions in .golangci.yml so the library is tested with the most recent golang, even if it supports an older one.

I've adapted the `.golangci.yml` from another Elastic project, but it seems those `go: ...` versions on the linters have no effect, it should be on the `run` section instead. When it's empty, it defaults to the `go.mod` version and/or  `GOVERSION` env var, which I think is the optimal behaviour for the linters. It also had a few invalid/deprecate settings that I fixed on the last commit.

**Pull request merged**
